name: Adam R Barnett
favicon: null
layout_spectrum: 0.92358
typography_spectrum: 0.34074
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.17970318696461618
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
