name: Adam R Barnett
favicon: null
layout_spectrum: 0
typography_spectrum: 0.34074
title: Adam R Barnett
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#888888'
    - '#616161'
    - '#b2b2b2'
  brandStrength: 0.17970318696461618
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0
purpose: []
