name: Adam R Barnett
favicon: null
layout_spectrum: 0.92358
typography_spectrum: 0.34074
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0605'
    - '#343235'
    - '#ffffff'
    - '#ab7538'
    - '#ffa42a'
  brandStrength: 0.17970318696461618
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
